-- Bootstrap para la base creada por el entrypoint oficial de Postgres.
-- Usa POSTGRES_DB y POSTGRES_USER definidos en docker-compose/.env.

CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS rag;

GRANT USAGE ON SCHEMA public TO CURRENT_USER;
GRANT USAGE, CREATE ON SCHEMA rag TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA rag
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA rag
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO CURRENT_USER;

SELECT current_user;
SELECT current_database();
